name: CI

on:
  push:
    branches:
    - * 
  pull_request:
    branches: 
    - * 
  workflow_dispatch:

jobs:
  build:
    name: Building via Node.js ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [ '14' ]
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Setup Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Compile Typescript
      run: |
        yarn
        yarn build
  style:
    name: ESLint checks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [ '14' ]
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run ESLint
        run: |
          yarn lint